name: 'Run BDD Tests'
description: 'Runs Cucumber BDD smoke tests using Playwright'

inputs:
  test-type:
    description: 'Type of tests to run (smoke, all, debug)'
    required: false
    default: 'smoke'

runs:
  using: 'composite'
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: |
        echo "📦 Installing Playwright browsers..."
        pnpm exec playwright install --with-deps chromium

    - name: Start development server
      shell: bash
      run: |
        echo "🚀 Starting Next.js development server..."
        pnpm run dev &
        
        # Wait for server to be ready
        echo "⏳ Waiting for server to start..."
        timeout 60 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done' || {
          echo "❌ Server failed to start within 60 seconds"
          exit 1
        }
        
        echo "✅ Server is ready at http://localhost:3000"

    - name: Run BDD tests
      shell: bash
      run: |
        echo "🥒 Running Cucumber BDD tests (type: ${{ inputs.test-type }})"

        case "${{ inputs.test-type }}" in
          smoke)
            echo "Running smoke tests..."
            pnpm run test:cucumber:smoke
            ;;
          all)
            echo "Running all tests..."
            pnpm run test:cucumber
            ;;
          debug)
            echo "Running tests in debug mode..."
            pnpm run test:cucumber:debug
            ;;
          *)
            echo "Unknown test type '${{ inputs.test-type }}', defaulting to smoke"
            pnpm run test:cucumber:smoke
            ;;
        esac

        echo "✅ BDD tests completed successfully"
