import DRImg from '@/public/images/projects/dr/dr-preview.png';
import RPImg from '@/public/images/projects/rpo/tn_2026.png';
import SSPImg from '@/public/images/projects/ssp/tn_1_2026.png';

import { ProjectData } from '../components/organisms/ProjectsView.component';

export const PROJECTS: ProjectData[] = [
  {
    category: 'web',
    featured: true,
    type: 'Featured Project',
    title: 'Driver Recommendations',
    summary:
      'A full-stack solution to provide recommendations for predicted trips to taxi drivers, powered by a machine learning model to predict supply and demand.',
    img: DRImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'React',
      'Styled Components',
      'TypeScript',
      'MongoDB',
      'HashiCorp Nomad',
      'Docker',
      'REST APIs',
      'Microservices',
      'Node',
      'Express',
      'Google Maps API',
    ],
  },
  {
    category: 'web',
    featured: false,
    type: '',
    title: 'Semantic Search Portal',
    summary:
      'A semantic search engine that ingests and indexes audio recordings, video recordings, and text content. You can then search by keywords. The portal ingests content by upload, filesystem path, or API calls.',
    img: SSPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/ssp-2026.mp4',
    link: '#',
    stack: [
      'Java 17',
      'Spring Boot 3',
      'JPA',
      'Flyway',
      'JUnit',
      'React',
      'TypeScript',
      'Vite',
      'Material-UI',
      'Emotion',
      'Python 3.12',
      'FastAPI',
      'faster-whisper',
      'WhisperModel',
      'ChromaDB',
      'all-MiniLM-L6-v2',
      'Docker',
      'PostgreSQL',
      'REST API',
    ],
  },
  {
    category: 'web',
    featured: false,
    type: '',
    title: 'Route Planning Optimization Engine',
    summary: 'A concept route planning optimization engine built during a hackathon!',
    img: RPImg,
    videoSrc: 'https://projects.minademian.com/docs-lib/route-planning.mp4',
    link: '#',
    stack: [
      'Java 23',
      'Spring Boot 3',
      'JPA',
      'JavaScript',
      'Vite',
      'AWS Location Services API',
      'REST API',
    ],
  },
  {
    category: 'mobile',
    featured: true,
    type: '',
    title: 'Koptiska liturgiska texter',
    summary: 'A digital repository for liturgical (communal) prayers in Arabic and Swedish, for the Coptic Orthodox Church in Scandinavia',
    img: RPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'React Native',
      'SQLite',
    ],
  },
  {
    category: 'mobile',
    featured: true,
    type: '',
    title: 'KooM!',
    summary: 'An alarm app with no snooze option. Get up or suffer the consequences.',
    img: RPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'React Native',
      'MMKV',
      'Expo',
      'expo-audio',
      'expo-video',
    ],
  },
  {
    category: 'oss',
    featured: true,
    type: '',
    title: 'static-deploy-kit',
    summary: 'A React Native alarm app with no snooze option. Get up or suffer the consequences.',
    img: RPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'GitHub Actions',
      'YAML',
    ],
  },
  {
    category: 'oss',
    featured: true,
    type: '',
    title: 'server-utilities',
    summary: 'A React Native alarm app with no snooze option. Get up or suffer the consequences.',
    img: RPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'bash',
    ],
  },
  {
    category: 'oss',
    featured: true,
    type: '',
    title: 'yarn-shell-completion',
    summary: 'A React Native alarm app with no snooze option. Get up or suffer the consequences.',
    img: RPImg,
    videoSrc: 'https://d1n1dt082182bs.cloudfront.net/DR-showcase-2025.mp4',
    link: '#',
    stack: [
      'bash',
    ],
  },
];