name: 'Build Project'
description: 'Builds the Next.js project and verifies output'

inputs:
  build-command:
    description: 'Build command to run'
    required: false
    default: 'pnpm run build'
  deployment-type:
    description: 'Type of deployment (sandbox, release, production)'
    required: false
    default: 'production'
  branch-name:
    description: 'Branch name for sandbox deployments'
    required: false
    default: ''
  git-tag:
    description: 'Git tag for release deployments'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build project
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.deployment-type }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        GIT_TAG: ${{ inputs.git-tag }}
      run: |
        echo "🏗️  Building with deployment context:"
        echo "   Type: $DEPLOYMENT_TYPE"
        echo "   Branch: $BRANCH_NAME"
        echo "   Tag: $GIT_TAG"
        
        ${{ inputs.build-command }}

    - name: Verify build output
      shell: bash
      run: |
        echo "Build completed successfully!"
        if [ -d "out" ]; then
          echo "Found out/ directory:"
          ls -la out/ | head -10
        elif [ -d "dist" ]; then
          echo "Found dist/ directory:"
          ls -la dist/ | head -10
        elif [ -d ".next" ]; then
          echo "Found .next/ directory:"
          ls -la .next/ | head -10
        else
          echo "Build directory not found, but build completed successfully"
        fi
