name: E2E Tests

# Permissions needed for commenting on PRs and issues
permissions:
  contents: read  # Needed to checkout repository
  pull-requests: write  # Needed to comment on PRs
  issues: write  # Needed to comment on issues

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to test against'
        required: false
        type: string
        default: 'development'
      fail_on_error:
        description: 'Whether to fail the workflow if tests fail (true = blocking, false = non-blocking)'
        required: false
        type: boolean
        default: true
      skip-e2e:
        description: 'Whether to skip E2E tests (from commit type check)'
        required: false
        type: string
        default: 'false'
    outputs:
      test-results:
        description: 'E2E test results (passed/failed)'
        value: ${{ jobs.e2e-tests.outputs.test-results }}
      tests-passed:
        description: 'Whether E2E tests passed (true/false)'
        value: ${{ jobs.e2e-tests.outputs.test-results == 'passed' }}

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      test-results: ${{ steps.test-results.outputs.results }}

    steps:
      - name: Notify E2E skip
        if: inputs.skip-e2e == 'true'
        run: |
          echo "🔧 E2E Tests Skipped for CI/Chore Commit"
          echo ""
          echo "💡 E2E tests are skipped for commits that:"
          echo "   - Start with 'ci' (continuous integration changes)"
          echo "   - Start with 'chore' (maintenance/housekeeping tasks)"
          echo "   - Start with 'docs' (documentation changes)"
          echo ""
          echo "This speeds up CI/CD pipeline for GitHub Actions changes that don't affect application functionality."

      - name: Checkout repository
        if: inputs.skip-e2e != 'true'
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        if: inputs.skip-e2e != 'true'
        uses: ./.github/actions/setup-node-pnpm

      - name: Install Playwright Browsers
        if: inputs.skip-e2e != 'true'
        run: pnpm exec playwright install --with-deps chromium firefox webkit

      - name: Run E2E tests
        if: inputs.skip-e2e != 'true'
        id: run-tests
        run: |
          pnpm exec playwright test --reporter=github
        continue-on-error: true

      - name: Set test results
        id: test-results
        run: |
          if [ "${{ inputs.skip-e2e }}" == "true" ]; then
            echo "results=skipped" >> $GITHUB_OUTPUT
          elif [ ${{ steps.run-tests.outcome }} == "success" ]; then
            echo "results=passed" >> $GITHUB_OUTPUT
          else
            echo "results=failed" >> $GITHUB_OUTPUT
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() && inputs.skip-e2e != 'true'
        with:
          name: playwright-report-${{ github.run_id }}
          path: |
            playwright-report/
            test-results/
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure() && inputs.skip-e2e != 'true'
        with:
          name: playwright-videos-${{ github.run_id }}
          path: test-results/*/video.webm
          retention-days: 7
          if-no-files-found: ignore

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const testResults = '${{ steps.test-results.outputs.results }}';
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            let body;
            if (testResults === 'skipped') {
              body = `⚡ **E2E Tests Skipped**

              E2E tests were skipped for this CI/Chore/Docs commit to speed up the pipeline.

              E2E tests are automatically skipped for commits that start with:
              - \`ci\` (continuous integration changes)
              - \`chore\` (maintenance/housekeeping tasks)
              - \`docs\` (documentation changes)

              > This optimization reduces pipeline time for GitHub Actions changes that don't affect application functionality.`;
            } else if (testResults === 'passed') {
              body = `✅ **E2E Tests Passed**

              All end-to-end tests are passing successfully!

              [View full test report](${runUrl})`;
            } else {
              body = `❌ **E2E Tests Failed**

              Some end-to-end tests are failing. Please check the test results and fix any issues before merging.

              [View full test report](${runUrl})
              [Download test artifacts](${runUrl}#artifacts)`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail job if tests failed
        if: steps.test-results.outputs.results == 'failed' && inputs.fail_on_error == true
        run: |
          echo "E2E tests failed. Failing the job."
          exit 1

      - name: Log test failure (non-blocking)
        if: steps.test-results.outputs.results == 'failed' && inputs.fail_on_error == false
        run: |
          echo "⚠️ E2E tests failed, but continuing pipeline as this is configured as non-blocking."
          echo "Check the test results and artifacts for details."
